/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.promedia.sentepos.ui;

import java.awt.Frame;
import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author shaffic
 */
public class Dashboard extends javax.swing.JFrame {
    
    private String username = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username) {
        initComponents();
        this.username = username;
        usernameLabel.setText("User: "+ username);
    }
    

    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        posLabel = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        efrisLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SentePOS — Dashboard");
        setBackground(new java.awt.Color(102, 0, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        setupLabel.setBackground(new java.awt.Color(0, 102, 0));
        setupLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        setupLabel.setForeground(new java.awt.Color(255, 255, 255));
        setupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setupLabel.setText("Setup");
        setupLabel.setOpaque(true);
        setupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setupLabelMouseClicked(evt);
            }
        });

        salesLabel.setBackground(new java.awt.Color(255, 204, 153));
        salesLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(0, 0, 0));
        salesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesLabel.setText("Sales");
        salesLabel.setOpaque(true);
        salesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesLabelMouseClicked(evt);
            }
        });

        posLabel.setBackground(new java.awt.Color(102, 0, 204));
        posLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        posLabel.setForeground(new java.awt.Color(255, 255, 255));
        posLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posLabel.setText("POS");
        posLabel.setOpaque(true);
        posLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posLabelMouseClicked(evt);
            }
        });

        productLabel.setBackground(new java.awt.Color(204, 0, 51));
        productLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        productLabel.setForeground(new java.awt.Color(255, 255, 255));
        productLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel.setText("Products");
        productLabel.setOpaque(true);
        productLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLabelMouseClicked(evt);
            }
        });

        efrisLabel.setBackground(new java.awt.Color(51, 102, 255));
        efrisLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        efrisLabel.setForeground(new java.awt.Color(255, 255, 51));
        efrisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        efrisLabel.setText("EFRIS");
        efrisLabel.setOpaque(true);
        efrisLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                efrisLabelMouseClicked(evt);
            }
        });

        userLabel.setBackground(new java.awt.Color(0, 204, 204));
        userLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Users");
        userLabel.setOpaque(true);

        usernameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(efrisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(usernameLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(efrisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setupLabelMouseClicked

        BusinessSetupFrame f = new BusinessSetupFrame();
        f.setLocationRelativeTo(this);
            f.setVisible(true);
    }//GEN-LAST:event_setupLabelMouseClicked

    private void posLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posLabelMouseClicked
        PosFrame pf = new PosFrame();
            pf.setLocationRelativeTo(this);
            pf.setVisible(true);
    }//GEN-LAST:event_posLabelMouseClicked

    private void salesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesLabelMouseClicked
        Window owner = SwingUtilities.getWindowAncestor(salesLabel);
            JDialog dlg = new SalesListDialog(owner instanceof Frame ? (Frame) owner : null);
            dlg.setLocationRelativeTo(owner);
            dlg.setVisible(true);
    }//GEN-LAST:event_salesLabelMouseClicked

    private void efrisLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efrisLabelMouseClicked
        // open as a dialog
            SalesFiscalisationDialog.open(this);

            // or embed as a tab:
            // yourTabbedPane.addTab("Fiscalisation", new SalesFiscalisationPanel());
    }//GEN-LAST:event_efrisLabelMouseClicked

    private void productLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseClicked
        ProductsListFrame f = new ProductsListFrame();
            f.setLocationRelativeTo(this);
            f.setVisible(true);
    }//GEN-LAST:event_productLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel efrisLabel;
    private javax.swing.JLabel posLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JLabel setupLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
