/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.promedia.sentepos.ui;

import com.promedia.sentepos.efris.EfrisClient;
import com.promedia.sentepos.license.LicenseManager;
import com.promedia.sentepos.service.EfrisDictionaryService;
import java.awt.Frame;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author shaffic
 */
public class Dashboard extends javax.swing.JFrame {
    
    private String username = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username) {
        initComponents();
        this.username = username;
        usernameLabel.setText("User: "+ username);
        // Disable Licesing
        //startExpiryMonitor();

    }
    

    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void startExpiryMonitor() {
    Timer timer = new Timer(10000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (!LicenseManager.isTrialActive()) {
                JOptionPane.showMessageDialog(null,
                        "Your trial has expired. SentePOS will now close.",
                        "Trial Expired",
                        JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
        }
    });

    timer.start();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        posLabel = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        efrisLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        creditNotesLabel = new javax.swing.JLabel();
        unitOfMeasure = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SentePOS — Dashboard");
        setBackground(new java.awt.Color(0, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        setupLabel.setBackground(new java.awt.Color(0, 102, 0));
        setupLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        setupLabel.setForeground(new java.awt.Color(255, 255, 255));
        setupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setupLabel.setText("Setup");
        setupLabel.setOpaque(true);
        setupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setupLabelMouseClicked(evt);
            }
        });

        salesLabel.setBackground(new java.awt.Color(255, 204, 153));
        salesLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(0, 0, 0));
        salesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesLabel.setText("Sales");
        salesLabel.setOpaque(true);
        salesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesLabelMouseClicked(evt);
            }
        });

        posLabel.setBackground(new java.awt.Color(102, 0, 204));
        posLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        posLabel.setForeground(new java.awt.Color(255, 255, 255));
        posLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posLabel.setText("POS");
        posLabel.setOpaque(true);
        posLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posLabelMouseClicked(evt);
            }
        });

        productLabel.setBackground(new java.awt.Color(204, 0, 51));
        productLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        productLabel.setForeground(new java.awt.Color(255, 255, 255));
        productLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel.setText("Products");
        productLabel.setOpaque(true);
        productLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLabelMouseClicked(evt);
            }
        });

        efrisLabel.setBackground(new java.awt.Color(51, 102, 255));
        efrisLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        efrisLabel.setForeground(new java.awt.Color(255, 255, 51));
        efrisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        efrisLabel.setText("EFRIS");
        efrisLabel.setOpaque(true);
        efrisLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                efrisLabelMouseClicked(evt);
            }
        });

        userLabel.setBackground(new java.awt.Color(0, 204, 204));
        userLabel.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("Users");
        userLabel.setOpaque(true);

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("jLabel1");

        creditNotesLabel.setBackground(new java.awt.Color(0, 153, 153));
        creditNotesLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        creditNotesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditNotesLabel.setText("Credit Notes");
        creditNotesLabel.setOpaque(true);
        creditNotesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditNotesLabelMouseClicked(evt);
            }
        });

        unitOfMeasure.setText("Unit Of Measure");
        unitOfMeasure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unitOfMeasureMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("For Support      WhatsApp: 0775200442    Calls: +1 224 373 0803");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unitOfMeasure, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creditNotesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(efrisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(posLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(115, 115, 115)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(usernameLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(efrisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(creditNotesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitOfMeasure, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setupLabelMouseClicked

        BusinessSetupFrame f = new BusinessSetupFrame();
        f.setLocationRelativeTo(this);
            f.setVisible(true);
    }//GEN-LAST:event_setupLabelMouseClicked

    private void posLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posLabelMouseClicked
        PosFrame pf = new PosFrame();
            pf.setLocationRelativeTo(this);
            pf.setVisible(true);
    }//GEN-LAST:event_posLabelMouseClicked

    private void salesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesLabelMouseClicked
        Window owner = SwingUtilities.getWindowAncestor(salesLabel);
            JDialog dlg = new SalesListDialog(owner instanceof Frame ? (Frame) owner : null);
            dlg.setLocationRelativeTo(owner);
            dlg.setVisible(true);
    }//GEN-LAST:event_salesLabelMouseClicked

    private void efrisLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efrisLabelMouseClicked
        // open as a dialog
            SalesFiscalisationDialog.open(this);

            // or embed as a tab:
            // yourTabbedPane.addTab("Fiscalisation", new SalesFiscalisationPanel());
    }//GEN-LAST:event_efrisLabelMouseClicked

    private void productLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseClicked
        ProductsListFrame f = new ProductsListFrame();
            f.setLocationRelativeTo(this);
            f.setVisible(true);
    }//GEN-LAST:event_productLabelMouseClicked

    private void creditNotesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditNotesLabelMouseClicked
        // TODO add your handling code here:
         CreditNoteListPanel.openInDialog(this); // To be Deleted
       // new CreditNotesListFrame().setVisible(true);
        
    }//GEN-LAST:event_creditNotesLabelMouseClicked

    
    private void unitOfMeasureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unitOfMeasureMouseClicked
        try {
            // somewhere in your admin/settings screen:
            EfrisClient client = new EfrisClient();
            int count = client.syncUomDictionaryToDb(null);
            JOptionPane.showMessageDialog(this,
                    "Synced " + count + " Unit of Measure entries from EFRIS.");
            
            
            /**
             * EfrisClient client = new EfrisClient();
             * EfrisClient.Result r = null;
             * try {
             * r = client.fetchUnitOfMeasureDictionary(null);
             * } catch (Exception ex) {
             * System.getLogger(Dashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             * }
             * 
             * System.out.println(r.ok);
             * System.out.println(r.innerContentJson);
             */} catch (Exception ex) {
            System.getLogger(Dashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_unitOfMeasureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditNotesLabel;
    private javax.swing.JLabel efrisLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel posLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JLabel setupLabel;
    private javax.swing.JLabel unitOfMeasure;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
